"""Storage subpackage — protocols + SQLite adapters + filters."""

from pydocs_mcp.storage.errors import UnitOfWorkNotEnteredError
from pydocs_mcp.storage.filters import (
    All,
    Any_,
    FieldEq,
    FieldIn,
    FieldLike,
    FieldSpec,
    Filter,
    FilterFormat,
    MetadataFilterFormat,
    MetadataSchema,
    MultiFieldFormat,
    Not,
    format_registry,
)
from pydocs_mcp.storage.protocols import (
    ChunkStore,
    DocumentTreeStore,
    FilterAdapter,
    HybridSearchable,
    ModuleMemberStore,
    PackageStore,
    ReferenceStore,
    TextSearchable,
    UnitOfWork,
    VectorSearchable,
)
from pydocs_mcp.storage.sqlite import (
    SqliteChunkRepository,
    SqliteDocumentTreeStore,
    SqliteFilterAdapter,
    SqliteLexicalStore,
    SqliteModuleMemberRepository,
    SqlitePackageRepository,
    SqliteReferenceStore,
    SqliteUnitOfWork,
    SqliteVectorStore,
)

__all__ = [
    "All",
    "Any_",
    "ChunkStore",
    "DocumentTreeStore",
    "FieldEq",
    "FieldIn",
    "FieldLike",
    "FieldSpec",
    "Filter",
    "FilterAdapter",
    "FilterFormat",
    "HybridSearchable",
    "MetadataFilterFormat",
    "MetadataSchema",
    "ModuleMemberStore",
    "MultiFieldFormat",
    "Not",
    "PackageStore",
    "ReferenceStore",
    "SqliteChunkRepository",
    "SqliteDocumentTreeStore",
    "SqliteFilterAdapter",
    "SqliteLexicalStore",
    "SqliteModuleMemberRepository",
    "SqlitePackageRepository",
    "SqliteReferenceStore",
    "SqliteUnitOfWork",
    "SqliteVectorStore",
    "TextSearchable",
    "UnitOfWork",
    "UnitOfWorkNotEnteredError",
    "VectorSearchable",
    "format_registry",
]
